# task
save_codes: ['modules', 'tasks']
amp: false
seed: 42
debug: false

#############
# data format
#############
audio_num_mel_bins: 80
audio_sample_rate: 48000
fft_size: 1024  # Extra window size is filled with 0 paddings to match this parameter
win_size: 1024
hop_size: 256
fmin: 80
fmax: 7600  # To be increased/reduced depending on data.
f0_min: 30
f0_max: 12000
mel_vmin: -6
mel_vmax: 1.5
loud_norm: false
raw_data_dir: ''
processed_data_dir: ''
binary_data_dir: ''
binarizer_cls: data_gen.tts.base_binarizer.BaseBinarizer

binarization_args:
  shuffle: false
  with_mel: true
  with_wav: false
  with_align: true
  with_spk_embed: false
  with_f0: true
  with_f0cwt: false
  with_linear: false
  with_w2v2_feat: false
  trim_eos_bos: false
  min_sil_duration: 0.1
  train_range: [ 200, -1 ]
  test_range: [ 0, 100 ]
  valid_range: [ 100, 200 ]
use_word_input: false
use_pitch_embed: true

#############
# dataset in training
#############
endless_ds: true
min_frames: 0
max_frames: 4000
frames_multiple: 1
max_input_tokens: 1550
ds_workers: 1
sort_by_len: true
pin_memory: false

#########
# model
#########
use_spk_id: false
use_spk_embed: false
hidden_size: 256

###########
# optimization
###########
lr: 0.0005
scheduler: warmup # rsqrt|warmup|none
warmup_updates: 4000
optimizer_adam_beta1: 0.9
optimizer_adam_beta2: 0.98
weight_decay: 0
clip_grad_norm: 1
clip_grad_value: 0
scheduler_lr_step_size: 500
scheduler_lr_gamma: 0.998

###########
# train and eval
###########
train_set_name: 'train'
train_sets: ''
load_ckpt: ''
accumulate_grad_batches: 1
max_epochs: 1000
max_updates: 1000000
max_tokens: 40000
max_sentences: 100000
resume_from_checkpoint: 0
rename_tmux: false

valid_set_name: 'valid'
num_valid_plots: 10
max_valid_sentences: 1
max_valid_tokens: 60000
valid_infer_interval: 10000
save_gt: true
save_f0: false
gen_dir_name: ''
print_nan_grads: false
save_best: false
num_ckpt_keep: 3
tb_log_interval: 100
num_sanity_val_steps: 5  # steps of validation at the beginning
check_val_every_n_epoch: 10
val_check_interval: 2000
valid_monitor_key: 'val_loss'
valid_monitor_mode: 'min'
eval_max_batches: -1

test_set_name: 'test'
test_ids: [ ]
test_input_yaml: ''
profile_infer: false
out_wav_norm: false

# inference
input_process_name: none

